/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as RCodeHistoryRouteImport } from './routes/r.$code.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeHistoryRoute = RCodeHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => RCodeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/r/$code': typeof RCodeRouteWithChildren
  '/r/$code/history': typeof RCodeHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/r/$code': typeof RCodeRouteWithChildren
  '/r/$code/history': typeof RCodeHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/r/$code': typeof RCodeRouteWithChildren
  '/r/$code/history': typeof RCodeHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/r/$code' | '/r/$code/history'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/r/$code' | '/r/$code/history'
  id: '__root__' | '/' | '/r/$code' | '/r/$code/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RCodeRoute: typeof RCodeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code/history': {
      id: '/r/$code/history'
      path: '/history'
      fullPath: '/r/$code/history'
      preLoaderRoute: typeof RCodeHistoryRouteImport
      parentRoute: typeof RCodeRoute
    }
  }
}

interface RCodeRouteChildren {
  RCodeHistoryRoute: typeof RCodeHistoryRoute
}

const RCodeRouteChildren: RCodeRouteChildren = {
  RCodeHistoryRoute: RCodeHistoryRoute,
}

const RCodeRouteWithChildren = RCodeRoute._addFileChildren(RCodeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RCodeRoute: RCodeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
